# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: tictactoe.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer

PeerOrgs:
  # ---------------------------------------------------------------------------
  # Player1
  # ---------------------------------------------------------------------------
  - Name: Player1
    Domain: player1.tictactoe.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Player2: See "Player1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Player2
    Domain: player2.tictactoe.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
