# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.tictactoe.com:
  peer0.player1.tictactoe.com:
  peer0.player2.tictactoe.com:

networks:
  tttnet:

services:

  orderer.tictactoe.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.tictactoe.com
    container_name: orderer.tictactoe.com
    networks:
      - tttnet

  ca.player1.tictactoe.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-player1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.player1.tictactoe.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${PLAYER1_CK}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.player1.tictactoe.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${PLAYER1_CK} -b admin:adminpw -d'
    volumes:
      - ${FABRIC_CFG_PATH}/crypto-config/peerOrganizations/player1.tictactoe.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.player1.tictactoe.com
    networks:
      - tttnet

  peer0.player1.tictactoe.com:
    container_name: peer0.player1.tictactoe.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player1.tictactoe.com
    networks:
      - tttnet

  peer0.player2.tictactoe.com:
    container_name: peer0.player2.tictactoe.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player2.tictactoe.com
    networks:
      - tttnet

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.player1.tictactoe.com:7051
      - CORE_PEER_LOCALMSPID=Player1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tictactoe.com/peers/peer0.player1.tictactoe.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tictactoe.com/peers/peer0.player1.tictactoe.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tictactoe.com/peers/peer0.player1.tictactoe.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tictactoe.com/users/Admin@player1.tictactoe.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ${FABRIC_CFG_PATH}/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ${FABRIC_CFG_PATH}/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.tictactoe.com
      - peer0.player1.tictactoe.com
      - peer0.player2.tictactoe.com
    networks:
      - tttnet
