# Copyright Stefan Prisca. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.tfc.com:
  peer0.player1.tfc.com:
  peer0.player2.tfc.com:
  peer0.player3.tfc.com:
  peer0.player4.tfc.com:
  peer0.player5.tfc.com:

networks:
  tfcn:
services:

  orderer.tfc.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.tfc.com
    container_name: orderer.tfc.com
    networks:
      - tfcn

  peer0.player1.tfc.com:
    container_name: peer0.player1.tfc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player1.tfc.com
    networks:
      - tfcn

  peer0.player2.tfc.com:
    container_name: peer0.player2.tfc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player2.tfc.com
    networks:
      - tfcn

  peer0.player3.tfc.com:
    container_name: peer0.player3.tfc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player3.tfc.com
    networks:
      - tfcn

  peer0.player4.tfc.com:
    container_name: peer0.player4.tfc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player4.tfc.com
    networks:
      - tfcn

  peer0.player5.tfc.com:
    container_name: peer0.player5.tfc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.player5.tfc.com
    networks:
      - tfcn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.player1.tfc.com:7051
      - CORE_PEER_LOCALMSPID=Player1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tfc.com/peers/peer0.player1.tfc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tfc.com/peers/peer0.player1.tfc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tfc.com/peers/peer0.player1.tfc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/player1.tfc.com/users/Admin@player1.tfc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ${FABRIC_CFG_PATH}/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ${FABRIC_CFG_PATH}/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.tfc.com
      - peer0.player1.tfc.com
      - peer0.player2.tfc.com
      - peer0.player3.tfc.com
      - peer0.player4.tfc.com
      - peer0.player5.tfc.com
    networks:
      - tfcn
